
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-api
  annotations:
    argocd.argoproj.io/sync-wave : "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-container
        image: busybox  # 轻量级 Linux 镜像
        command: ["/bin/sh", "-c", "echo 'Hello World!'; tail -f /dev/null"]  # 输出后保持运行



